### PR TITLE
Scripts : Add ci script

### PR DESCRIPTION
**Pull request by qrr1995**
### What problem does this PR solve? 
Upload scripts from Jenkins to make CI logic could be version-controlled in github .
I would set Jenkins pipeline to load the scripts   after this PR is merged later.

### CODE REVIEW

**Comment by GregoryIan** [comment]
LGTM

**Comment by GregoryIan** [comment]
@july2993 @suzaku PTAL

**Comment by GregoryIan** [comment]
@qrr1995 do we need to add this script into 2.1/3.0/3.1 branch

**Comment by qrr1995** [comment]
Not need to do so,  jenkins is supposed to  load scipts from:   
- HEAD of `master`  for PR which is not on `master` branch such as `release-2.1` and `release-3.0`
- HEAD of PR  which is on `master` branch.  (for groovy debugging concern)

@GregoryIan @july2993

**Comment by july2993** [comment]
> Not need to do so, jenkins is supposed to load scipts from:
> 
> * HEAD of `master`  for PR which is not on `master` branch such as `release-2.1` and `release-3.0`
> * HEAD of PR  which is on `master` branch.  (for groovy debugging concern)
> 
> @GregoryIan @july2993

got it, you can merge it once ci is ready.

**Pull request merged**
