### PR TITLE
drainer/: Change unreasonable buff size and reduce memory usage

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
the `maxBinlogItemCount` var will affect the job buffer size in an unreasonable way.

In syncer.sync will work like this

```
// where will be worker-count goroutine to run this
for {
    get job from "jobChan chan *job"
    if reach some condition {
          execute the pending job(execute sql)
     } else {
         continue
     }
}
```
note execute the sql may take times, and not consume the job chan.
so the upstream may block at add job into the chan, and also will not add job the other `sync` job chan.

### What is changed and how it works?
avoid any buffer at upstream  to much mem and not decrease performance, and don't make buffer size of job chan depent on `maxBinlogItemCount`

Screen Shot 2019-08-30 at 2 43 43 PM

the flowing v1 means https://github.com/pingcap/tidb-binlog/pull/735/commits/f9e4589de8b934f3dcfcdee097fd3c9206d3d459
v2 means one more commit https://github.com/pingcap/tidb-binlog/pull/735/commits/3074b3bb6b9e526eccbb036377a94473b167df5e

before 10:53   version: v2.1.16 maxBinlogItemCount=16
start at 10:53   version: v1  maxBinlogItemCount=16
start at 30 11:17   version:v2.1.16   maxBinlogItemCount=64k (the previous default value)
start at 30 11:47   version: v1 maxBinlogItemCount=0

all using worker-count = 256, txn-batch = 20
note when the drainer restarts, the first 5 minutes will use safe-mode, the event metrics count the changed events.

## Another test:
the upstream data one binlog near 60M

start at 19:25: version: v1
start at 19:45: version: v2
Screen Shot 2019-08-30 at 7 56 23 PM
Screen Shot 2019-08-30 at 7 56 14 PM

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by GregoryIan** [comment]
lgtm

**Comment by leoppro** [comment]
why ci is failed?

**Comment by july2993** [comment]
> why ci was failed?

i don't know, failed at `status` test, but not related to this pr.
(run ok locally and failed ci at another pr too-2.1)

**Comment by leoppro** [comment]
LGTM

**Comment by lichunzhu** [comment]
IMO, CI fails because drainer hasn't consumed the pump 8250's storaged binlogs in 15 seconds when closing pump. This problem can be replayed on my server.

**Comment by july2993** [comment]
> IMO, CI fails because drainer hasn't consumed the pump 8250's storaged binlogs in 15 seconds when closing pump. This problem can be reproduced on my server.

Is it something relate to this pr change? can you fix this?

**Comment by lichunzhu** [comment]
> > IMO, CI fails because drainer hasn't consumed the pump 8250's storaged binlogs in 15 seconds when closing pump. This problem can be reproduced on my server.
> 
> Is it something relate to this pr change? can you fix this?

I'm not so sure now. I'm working on that now and later I will get a conclusion.

**Comment by lichunzhu** [comment]
There is still 4s gap between drainer and pump after 15s. I guess when drainer has cache it can cache some binlogs from pump then drainer can still sort and execute the cached binlogs even though this pump is paused. Maybe `binlogChanSize` shouldn't be set to 0. Or we can set check time in `check_status` more bigger.

**Comment by july2993** [comment]
@lichunzhu PTAL, the root cause is when runs into the `status` test, it will start with commit-ts = 0 and fetch data from the oldest point.

**Pull request merged**
