### PR TITLE
*: update tidb dependency 

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close  https://github.com/pingcap/tidb-binlog/issues/1210

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note

- No release note

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by hi-rustin — APPROVED** [review]

**Comment by xiongjiwei** [comment]
@lichunzhu @hi-rustin need help merge

**Pull request merged**
