### PR TITLE
binlog loop back sync

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
cherry pick #879 #867 

### What is changed and how it works?
cherry pick #879 #867 

    Add sync mode config (#867)

    allow when the column number of downstream table mismatch with current schema.

    For the case bidirectional replication, we will execute the DDL at one side, for add or drop column
    the column number will mismatch.

    cluster A <-> cluster B

    drop column of table t at cluster A
    some DML of table t at cluster B will miss the column dropped compared to cluster A

    binlog loop back sync (#879)

    In the AA dual activity scenario, there is data write (DML) on both sides. The data of tidb cluster on both sides needs to be synchronized with each other，but avoid loopback synchronization，and ddl is only writed one side.

    add three variables in drainer.toml as identification to confirm need sync ddl or not and need set sync mark identification or not and sync identification id to Avoid loopback synchronization
    add configuration item
    loopback-control (true/false) set mark table identification or not and filter txn by mark table
    ddl-sync (true/false) sync ddl to downstream DB or not
    channel-id (integer) sync identification id，avoid loopback synchronization

### Check List 

Code changes

### CODE REVIEW

**Comment by july2993** [comment]
@suzaku @freemindLi PTAL

**Comment by freemindLi** [comment]
LGTM

**Pull request merged**
