### PR TITLE
drainer: fix placement policy compatibility

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1118 and close https://github.com/pingcap/tidb/issues/31611

### What is changed and how it works?
make drainer compatible with placement policy

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lichunzhu** [comment]
@glorv @lance6716 PTAL

**Review by lance6716 — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Pull request merged**
