### PR TITLE
 drainer: bugfix, handle "missing column" when a column is getting dropped 

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

Cherry-pick pingcap/tidb-binlog#803

### What is changed and how it works?

Upgrade TiDB to `github.com/pingcap/tidb v1.1.0-beta.0.20191120070053-5a7ecfeb94fd`.

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by suzaku** [comment]
@july2993 PTAL

**Pull request merged**
