### PR TITLE
Cherry pick advertise-addr related changes from master

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

Cherry pick and adapt the following 3 PRs:

1. https://github.com/pingcap/tidb-binlog/pull/629
1. https://github.com/pingcap/tidb-binlog/pull/637
1. https://github.com/pingcap/tidb-binlog/pull/634

### What is changed and how it works?

1. Support configuring advertise-addr for drainer
1. Check for empty host in config

### Check List 

Tests 

 - Unit test
 - Manual test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by ericsyh** [comment]
@GregoryIan @WangXiangUSTC @july2993 PTAL

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by july2993** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by july2993** [comment]
after this pr is this invalid?   `addr=0.0.0.0:8250 advertise-addr=192.168.10.10:8250`

**Comment by suzaku** [comment]
> after this pr is this invalid? `addr=0.0.0.0:8250 advertise-addr=192.168.10.10:8250`

This should be valid for drainer.
But since we didn't change the behavior of pump, `0.0.0.0` is invalid for pump.

**Pull request merged**
