### PR TITLE
[2.1] Make release2.1 run linters and pass ci `check`

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
make release 2.1 run linters and pass CI `check`
### What is changed and how it works?
cherry-pick #557 and #568

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
Sign the CLA? 🤔

**Comment by suzaku** [comment]
LGTM

**Pull request merged**
