### PR TITLE
release-3.1: merge release 3.0

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve? 

release-3.1: merge release 3.0

### What is changed and how it works?

git merge release 3.0 and resolve conflicts

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@july2993 PTAL

**Comment by july2993** [comment]
Note maybe need to update the dependency of pd/tidb for online reload of certificate

**Pull request merged**
