### PR TITLE
dependency: update binlog parser/tidb/etcd to release-6.0

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb-binlog/issues/1145

### What is changed and how it works?
Update drainer's parser/tidb/etcd to tidb master's version.

### Check List 

Tests 

 - Unit test

Code changes

 - None

Side effects

 - None

Related changes

 - None

### Release note

- No release note

### CODE REVIEW

**Comment by lichunzhu** [comment]
@lance6716 @glorv PTAL

**Review by lance6716 — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Comment by lichunzhu** [comment]
/run-integration-test

https://ci2.pingcap.net/blue/organizations/jenkins/binlog_ghpr_integration/detail/binlog_ghpr_integration/193/pipeline

**Pull request merged**
