### PR TITLE
refine gc strategy of pump (#646)

### PR DESCRIPTION
**Pull request by GregoryIan**
### What problem does this PR solve? 
most users forget to mark drainer offline using `binlogctl` after they stop drainer, It would block gc of pump, and then the pump will easily fill up the disk capacity because there are too many binlogs.

Regardless of ease of use or design, this design is unreasonable. There are two main reasons:
* when the disk space of the pump is full, the pump will be unavailable, which will have a great impact on the data and TiDB instance.
* drainer is a relatively separate tool and should not have too much impact on core system formation

### What is changed and how it works?
* pump only keeps binlog events whose ts <= current time - gc(days)
* issue a critical metrics while some drainer checkpoint is old than gc ts of pump，it means binlog that drainer need is purged

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by mahjonp** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by suzaku** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by GregoryIan** [comment]
@july2993 PTAL

**Pull request merged**
