### PR TITLE
binlogctl: Only show offline nodes when explicitly told so

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

Some users complain that pump/drainer nodes that have been turn off still appears in the list.

### What is changed and how it works?

Hide `offline` nodes by default, only show them when `-show-offline-nodes` is set.

### Check List 

Tests 

 - Manual test
    I set a drainer to `offline` and then check with `binlogctl drainers`.

Code changes

Side effects

Related changes

 - Need to update the documentation

### CODE REVIEW

**Comment by GregoryIan** [comment]
Good Job! LGTM

**Comment by suzaku** [comment]
@WangXiangUSTC 这块对应的文档在哪里？

**Comment by suzaku** [comment]
@WangXiangUSTC Could you show me the document that I need to update.

**Comment by WangXiangUSTC** [comment]
https://pingcap.com/docs-cn/v2.1/reference/tools/tidb-binlog/maintain/#binlogctl-工具
need update this doc @suzaku

**Comment by suzaku** [comment]
@WangXiangUSTC OK

**Comment by WangXiangUSTC** [comment]
@suzaku we can merge this pr now and update doc later, just make sure doc is updated before release

**Comment by suzaku** [comment]
https://github.com/pingcap/docs-cn/pull/1968

@WangXiangUSTC  Document updated.

**Pull request merged**
