### PR TITLE
mod: update tidb dependency to latest && fix incompatible problem

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve? 
update tidb dependency to latest && fix incompatible problem
### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release note
- update tidb dependency to latest to fix incompatible problem

### CODE REVIEW

**Comment by overvenus** [comment]
Does it compatible with v4.0.x tidb?

**Review by leoppro — DISMISSED** [review]

**Comment by leoppro** [comment]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by you06** [comment]
Will this PR be included in 4.0.10?

**Pull request merged**
