### PR TITLE
support TLS for components and downstream db

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
- Support TLS to connect mysql/TiDB (#894)
- support TLS for components (#904)
- Reload cert/key for every new conn (#927)

### What is changed and how it works?
pick #894 #904 #927 

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by july2993** [comment]
-config "$OUT_DIR/tidb-config.toml" \

**Comment by WangXiangUSTC** [comment]
LGTM

**Pull request merged**
