### PR TITLE
go.mod: Update parser version as newest tidb 3.0 uses

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
Update parser version as newest tidb 3.0 uses

### What is changed and how it works?
Update parser version as newest tidb 3.0 uses

### CODE REVIEW

**Comment by july2993** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
@lichunzhu @suzaku @leoppro PTAL

**Comment by leoppro** [comment]
LGTM

**Pull request merged**
