### PR TITLE
Makefile: Version get the latest v4.0 tag for master

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
Version get the latest v4.0 tag for master
so we can keep release3.0 and master don't diverse and show different version for `-V`
### What is changed and how it works?
add `-match 'v4.0*` opt for git description

### Check List 

Tests 

 - No code

Code changes

Side effects

 - Related changes

### CODE REVIEW

**Comment by lichunzhu** [comment]
LGTM

**Comment by kennytm** [comment]
>  so we can keep release3.0 and master don't diverse and show different version for -V

How would this work on the release-3.0 branch in the future?

**Comment by july2993** [comment]
> > so we can keep release3.0 and master don't diverse and show different version for -V
> 
> How would this work on the release-3.0 branch in the future?

we can change release-3.0 to match the v3.0 too if need

**Comment by kennytm** [comment]
So release-3.0 and master should diverge after this commit?

**Comment by july2993** [comment]
> So release-3.0 and master should diverge after this commit?

💔

**Comment by july2993** [comment]
looks we need to check the current branch in a `if .. else ..` way

**Comment by GregoryIan** [comment]
@leoppro PTAL

**Pull request closed without merging**
