### PR TITLE
Update parser as the latest version tidb use

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
Update parser as the latest version tidb use

### What is changed and how it works?
Update parser as the latest version tidb use

### Check List 

Tests

### CODE REVIEW

**Comment by suzaku** [comment]
@july2993 Please run `go mod tidy`.

**Comment by leoppro** [comment]
LGTM and fix CI please

**Comment by july2993** [comment]
> LGTM and fix CI please

fixed, pls approve and merge it.

**Pull request merged**
