### PR TITLE
drainer: make drainer compatiable with batch create tables job

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1113

### What is changed and how it works?
Support handling table schema info according to BR batch creates tables job.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
Use BR to batch create tables on upstream and update the restored tables. And in the manual test drainer can successfully sync the data for the specified tables.

Code changes

 - Has exported function/method change

Side effects

 - Possible performance regression

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Comment by lichunzhu** [comment]
/run-all-tests
@lance6716 PTAL

**Review by fengou1 — APPROVED** [review]
the previous local test show it works well when BR restore with binlog enabled cluster

**Pull request merged**
