### PR TITLE
ddl: change interface

### PR DESCRIPTION
**Pull request by xiongjiwei**
### Check List 

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1175

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note

- No release note

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

**Comment by hongyunyan** [comment]
cc @lichunzhu

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by gozssky — APPROVED** [review]

**Pull request merged**
