### PR TITLE
drainer: Remove unused waitGroup

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

`itemsWg` is not used anywhere.

### What is changed and how it works?

Remove the unused wait group.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lichunzhu** [comment]
LGTM

**Comment by suzaku** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
@lichunzhu There maybe something wrong with the master branch of Pd, the integration tests run successfully when I switched to release-3.0.

**Pull request merged**
