### PR TITLE
Change default cache count from 65536 to 512

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
A son PR of https://github.com/pingcap/tidb-binlog/pull/715.
Change default cache count from 65536 to workcount*batchsize
### What is changed and how it works?
Set default cache count as a variable of config. The default size is changed from 65536 `workcount*batchsize`.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by lichunzhu** [comment]
@suzaku So what do you think of the right value? How about 512? I'm not so sure about this.

**Comment by suzaku** [comment]
@lichunzhu Note that `cache-binlog-size` can not avoid OOM in all cases, because the buffer is not the only data structure consuming memory. For example, if the downstream is TiDB/MySQL, we'll be exeucting SQLs in bulk and the binlogs not executed yet are stored in a slice which might take up a lot of memory if `worker-count` and `batch-size` is set to large numbers.

What I am suggesting is that, since we are facing a complicated problem with no perfect solution right now, we'd better just use a simple solution that can make OOM less likely.

**Comment by lichunzhu** [comment]
@suzaku I understand what you mean now. Then what do you think of the limit value? Is 512 OK?

**Comment by july2993** [comment]
@lichunzhu just change to 512 but don't add the config in `SyncerConfig`

**Comment by suzaku** [comment]
512 or anything less than or equal to 1024 should be a safe choice, because in loader we also have a buffered channel which is hard coded to be 1024 in length.

**Comment by lichunzhu** [comment]
@suzaku @july2993 I have modified `defaultBinlogItemCount` from 65536 to 512, PTAL.

**Comment by suzaku** [comment]
@lichunzhu Just writing `512` may be more readable than `1 >> 9`?

**Comment by lichunzhu** [comment]
> @lichunzhu Just writing `512` may be more readable than `1 >> 9`?

Revised.

**Pull request merged**
