### PR TITLE
*: fix drainer can't send request correctly to pump when set compressor=gzip

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1152

### What is changed and how it works?
See https://github.com/pingcap/tidb-binlog/issues/1152#issuecomment-1216233918, add 4MB buffer for max grpc message size.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 Test playground with compressor, works correctly.

Related changes

 - Need to cherry-pick to the release branch

### Release note

- fix drainer can't send request correctly to pump when set compressor=gzip

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
How about moving the comment above the code?

**Pull request merged**
