### PR TITLE
update to go1.18

### LINKED ISSUE #1138: Upgrade go version to 1.18
# Enhancement
Upgrade go version to 1.18

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #1138

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### Release note

- No release note

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by lichunzhu** [comment]
/hold

looks like we need to update ci's go version first

**Comment by purelind** [comment]
replay binlog_ghpr_check with go1.18, replay ci url  https://ci2.pingcap.net/blue/organizations/jenkins/binlog_ghpr_check/detail/binlog_ghpr_check/424/pipeline/

**Comment by purelind** [comment]
replay binlog_ghpr_check with go1.18,  it passed https://ci2.pingcap.net/blue/organizations/jenkins/binlog_ghpr_check/detail/binlog_ghpr_check/428/pipeline/50

**Pull request merged**
