### PR TITLE
fix daily test case failure caused by auto_random

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

workaround test case failure caused by https://github.com/pingcap/tidb/issues/23235

### What is changed and how it works?

add clustered

### Check List 

Tests 

 - Unit test

Code changes

 - only test
 
Side effects

 - n/a
 
Related changes

 - Need to cherry-pick to the release branch 5.0

### Release note 

- No release note

### CODE REVIEW

**Comment by lysu** [comment]
@zhouqiang-cl  this will fix https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/binlog_ghpr_integration/detail/binlog_ghpr_integration/2527/pipeline

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by 3pointer** [comment]
LGTM

**Comment by zhouqiang-cl** [comment]
@lysu great, thank you, this pr is also should be in release-5.0

**Pull request merged**
