### PR TITLE
update parser in go.mode & go.sum to tidb release 2.1

### PR DESCRIPTION
**Pull request by lichunzhu**
### What is changed and how it works?
update parser in go.mode & go.sum to synchronize binlog with tidb.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by july2993** [comment]
can you help test this paser version can parse the `pre_split` ddl to make sure it works

**Comment by july2993** [comment]
@csuzhangxc @suzaku PTAL

**Comment by lichunzhu** [comment]
> can you help test this paser version can parse the `pre_split` ddl to make sure it works

@july2993 I will add some tests in another PR.

**Pull request merged**
