### PR TITLE
drainer: bugfix, handle "missing column" when a column is getting dro…

### PR DESCRIPTION
**Pull request by suzaku**
…pped

### What problem does this PR solve? 

Cherry-pick #803

### CODE REVIEW

**Comment by july2993** [comment]
pls fix ci

**Comment by suzaku** [comment]
@july2993 What's the default version of TiDB used when running integration tests for this branch?

**Comment by july2993** [comment]
> @july2993 What's the default version of TiDB used when running integration tests for this branch?

latest commit of branch release-2.1

**Comment by GregoryIan** [comment]
what's problem with CI?

**Comment by suzaku** [comment]
@GregoryIan It seems like the bug is not fixed by this PR. So the new integration tests failed.

**Comment by suzaku** [comment]
> > @july2993 What's the default version of TiDB used when running integration tests for this branch?
> 
> latest commit of branch release-2.1

We may need to wait until the corresponding [check-pick](https://github.com/pingcap/tidb/pull/13974) on TiDB is merged.

**Comment by leoppro** [comment]
we should handle `DdlSchemaState` at [storage.go#L986](https://github.com/pingcap/tidb-binlog/blob/release-2.1/pump/storage/storage.go#L986)

**Comment by leoppro** [comment]
rest LGTM

**Comment by suzaku** [comment]
> we should handle `DdlSchemaState` at [storage.go#L986](https://github.com/pingcap/tidb-binlog/blob/release-2.1/pump/storage/storage.go#L986)

**Comment by WangXiangUSTC** [comment]
> LGTM

ignore it

**Comment by leoppro** [comment]
LGTM

**Pull request merged**
