### PR TITLE
*: update tidb/tikv-client dependency to lastest

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb-binlog/issues/1170

### What is changed and how it works?
Update tikv-client dependencies to latest.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by lichunzhu** [comment]
@lance6716 @gozssky PTAL, thanks!

**Review by lance6716 — APPROVED** [review]

**Review by gozssky — APPROVED** [review]

**Pull request merged**
