### PR TITLE
drainer: remove deprecated syncer flash

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

1. The flash syncer is deprecated and is seldom used.
1. It takes a lot of effort to take care of the flash syncer when refactoring components of drainer

### What is changed and how it works?

Remove the obsolete syncer.

### Check List 

Tests 

 - Unit test

Code changes

 - Has interface methods change

    A dest db type is removed.

Side effects

 - Breaking backward compatibility

    Users of new version of binlog including this change will not be able to use flash as a dest db.

Related changes

 - Need to update the documentation

### CODE REVIEW

**Comment by GregoryIan** [comment]
need to update document, and maybe also ansible

**Comment by GregoryIan** [comment]
LGTM

**Comment by suzaku** [comment]
@july2993 PTAL

**Pull request merged**
