### PR TITLE
[release-2.1] pump: Add support to stop write at a limit avaliable space (#647)

### PR DESCRIPTION
**Pull request by july2993**
Default set it 10 gib

### What problem does this PR solve? 
cherry-pick https://github.com/pingcap/tidb-binlog/pull/647

Add a configuration to stop writes at a limit available space size.

### Check List 

Tests 

Code changes

### CODE REVIEW

**Comment by ericsyh** [comment]
@suzaku @WangXiangUSTC PTAL

**Comment by kennytm** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 pd=release-2.1

**Comment by july2993** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 pd=release-2.1

**Pull request merged**
