### PR TITLE
commit the dashboard and alter config about arbiter

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 
commit the dashboard and alter config about arbiter

### What is changed and how it works?
don't support ansible to deply arbiter cause it's simple.
so better just commit the files here

dashboard:
Screen Shot 2019-11-05 at 12 13 02 AM
Screen Shot 2019-11-05 at 12 13 10 AM

test and verify the alter:
Screen Shot 2019-11-05 at 12 43 32 AM

### Check List 

Tests 

deploy and verify it.

Code changes

- no

Side effects
- no

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### CODE REVIEW

**Comment by suzaku** [comment]
Document how to use these files in README or the documentation site?

**Comment by july2993** [comment]
docs in README_CN.md  @suzaku @GregoryIan PTAL

**Comment by july2993** [comment]
@GregoryIan PTAL

**Comment by GregoryIan** [comment]
@leoppro PTAL

**Comment by GregoryIan** [comment]
LGTM

**Pull request merged**
