### PR TITLE
testing, non code change

### PR DESCRIPTION
**Pull request by suzaku**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

### CODE REVIEW

**Comment by july2993** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by july2993** [comment]
/run-all-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=master tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=release-3.0 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=08d821931 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=pr/10981 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=pr/11029 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=pr/11019 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
/run-integration-tests tidb=pr/11018 tikv=release-3.0 pd=release-3.0

**Comment by suzaku** [comment]
Integration tests restore.

**Pull request closed without merging**
