### PR TITLE
drainer: Bugfix, should handle ActionModifySchemaCharsetAndCollate correctly

### PR DESCRIPTION
**Pull request by suzaku**
### What problem does this PR solve? 

Cherrypick #769

### What is changed and how it works?

Fix bug and add tests.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

### CODE REVIEW

**Comment by july2993** [comment]
LGTM

**Comment by suzaku** [comment]
/run-integration-tests tidb=release-2.1 pd=release-2.1 tikv=release-2.1

**Pull request merged**
